### ISSUE TITLE
How to enable Microphone and Headset in Thunderbird tab

### ISSUE THREAD

**Issue by dmcichy** [digitalkool/opengooglevoice#1]
I am running "Open Google Voice" on Thunderbird 78 in a tab.  UI looks great.  Problem is that on this Thunderbird tab, the MICROPHONE and SPEAKERS are not functional.  If you try to set the microphone or speakers from the Google Voice UI you see the following error message 

"To change this, give Google Voice permission to use your microphone "

Normally, to give Google Voice permissions, you would click on the LOCK ICON in the URL address bar.

The PROBLEM is that the clicking the LOCK ICON in a Thunderbird tab does precisely NOTHING, so I can't get to the Google Voice UI

**Comment by digitalkool** [comment]
It looks like the text box where the LOCK ICON and URL are displayed in a Thunderbird tab is not a URL address bar.  This is probably why nothing happens when you click on it.  I have not found a programmatic way to enable permissions or have them displayed in a thunderbird browser tab yet.  For the time being, I did come up with a workaround that should let you get past this. 

1. Go to the Thunderbird Edit -> Preferences -> General and scroll all the way down the page.
2. At the end of the page you should see a button called Config Editor.
3. Click it to open the about:config dialog.
4. Click on the I accept the risk! button.
5. In the search bar type media.navigator.permission.disabled.
6. Click on media.navigator.permission.disabled under Preference Name to select it.
7. Right mouse click to bring up the menu and select Toggle from the menu to change the value to true.
8. Close the window
9. Restart Thunderbird.

You should now be able to click on the icon the looks like headphones called Audio Setting in the Google Voice UI to select your devices.

IMPORTANT! - Be very careful when making changes in the about:config preferences.  I recommend you take the time to backup your Thunderbird profile before making changes.

**Comment by dmcichy** [comment]
Thank you kindly for the reply.  Up toggled **media.navigator.permission.disable** to **true** and and restarted Thunderbird and that actually worked.  The error messages about not having permissions went away and I was able to select a microphone and speakers for Google Voice.

Shouldn't this affect everyone using your AddOn if they don't have this setting in the config editor?

**Comment by dmcichy** [comment]
I can dial out now and received calls.  But I thought I'd make you aware of one more issue.  For whatever reason, if I dial out using Google Voice from any browser (like just calling time and temperature recording).  The audio from the connected call is normal.

If I do the same thing from your AddOn the audio from the connected party is slowed down to super slow-mo...  My laptop is a crazy fast powerhouse, So I'm not sure what is accounting for the seeming CPU struggle...

**Comment by dmcichy** [comment]
> I can dial out now and received calls. But I thought I'd make you aware of one more issue. For whatever reason, if I dial out using Google Voice from any browser (like just calling time and temperature recording). The audio from the connected call is normal.
> 
> If I do the same thing from your AddOn the audio from the connected party is slowed down to super slow-mo... My laptop is a crazy fast powerhouse, So I'm not sure what is accounting for the seeming CPU struggle...

Nevermind.  Turns out I had two instances of Thunderbird running on my machine.  A clean start got rid of the garbled slow-mo audio.  Great AddOn!

**Comment by dmcichy** [comment]
> Thank you kindly for the reply. Up toggled **media.navigator.permission.disable** to **true** and and restarted Thunderbird and that actually worked. The error messages about not having permissions went away and I was able to select a microphone and speakers for Google Voice.
> 
> Shouldn't this affect everyone using your AddOn if they don't have this setting in the config editor?

**UPDATE**
Thought I'd let you know that in addition to your advice to set 

> It looks like the text box where the LOCK ICON and URL are displayed in a Thunderbird tab is not a URL address bar. This is probably why nothing happens when you click on it. I have not found a programmatic way to enable permissions or have them displayed in a thunderbird browser tab yet. For the time being, I did come up with a workaround that should let you get past this.
> 
>     1. Go to the Thunderbird Edit -> Preferences -> General and scroll all the way down the page.
> 
>     2. At the end of the page you should see a button called Config Editor.
> 
>     3. Click it to open the about:config dialog.
> 
>     4. Click on the I accept the risk! button.
> 
>     5. In the search bar type media.navigator.permission.disabled.
> 
>     6. Click on media.navigator.permission.disabled under Preference Name to select it.
> 
>     7. Right mouse click to bring up the menu and select Toggle from the menu to change the value to true.
> 
>     8. Close the window
> 
>     9. Restart Thunderbird.
> 
> 
> You should now be able to click on the icon the looks like headphones called Audio Setting in the Google Voice UI to select your devices.
> 
> IMPORTANT! - Be very careful when making changes in the about:config preferences. I recommend you take the time to backup your Thunderbird profile before making changes.

**UPDATE** I thought I'd let you know that in addition to your suggestion to set **media.navigator.permission.disabled** to **true**, I made the following changes in Thunderbird's Configuration Editor.  These changes allow for being able to fully set all of the **Audio Settings**, including **Ringing**, **Microphone**, and **Speakers**.  media.navigator.permission.disabled=true only makes the red error messages for each of these go away, but you still cannot pick from available devices as it forces the system defaults for each.  media.setsinkid.enabled=true allows for full selection of any available device.

So now the ONLY think that doesn't work is **playback of voicemails**.  No matter what I do, clicking on the play button will not play back the voice mail.  **Thoughts?**


**SETTINGS REQUIRED IN THUNDERBIRD CONFIG EDITOR FOR OPEN GOOGLE VOICE TO WORK**
media.navigator.permission.disabled **true**
media.setsinkid.enabled **true**  

media.allowed-to-play.enabled **true**
media.autoplay.enabled **true**
media.block-autoplay-until-in-foreground **true**
media.playback.warnings-as-errors **true**
